### ISSUE TITLE
Einthusan does NOT play any movie

### ISSUE THREAD

**Issue by junejosheeraz** [humla/canadanepal-xbmc#8]
I am getting following in kodi.log when I select any movie to play;

`
02:18:34 T:2212   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.einthusan/?lang&mode=2&name=Tanu%20Weds%20Manu%20Returns&url=http%3a%2f%2fwww.einthusan.com%2fmovies%2fwatch.php%3fid%3d2679
02:18:34 T:2212   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.einthusan/?lang&mode=2&name=Tanu%20Weds%20Manu%20Returns&url=http%3a%2f%2fwww.einthusan.com%2fmovies%2fwatch.php%3fid%3d2679) failed
`

I decoded  the URL in Web Browser it lands on correct page and I can play movie normally. Its not working in Kodi. Kodi version 16.0

**Comment by humla** [comment]
Looking

**Comment by kodiokodi** [comment]
Thanks Humla... Pl do update the post if this get fix. I believe we can not play any movie now on plugin.

**Comment by ash0kgp** [comment]
Thank you Humla for looking into it. Kodi Version 16.0. Tried all pages. Video not working.

**Comment by Gujal00** [comment]
Fix available in pull request #9

**Comment by humla** [comment]
Merged your PR, but that is not enough, einthusan have changed the way they get the movie url via cdns. I have to find some time to fix it. If you want to have a go, just let me know and I will send you what I have so far.

**Comment by junejosheeraz** [comment]
Thanks guys for the help. @humla while we are waiting for your fix, is it possible for you to please release a quick update of a plugin so that we can test for you?

**Comment by Gujal00** [comment]
@humla i tested movies of different languages and bluray and all worked with the fix in #9 
Can you let me know an example of the changed url via cdn that is currently not working? I sure can give you a hand in trying to fix it. Cheers

**Comment by humla** [comment]
Hmm, it works for me now, which is a bit weird.. But I have released a new version v.1.2.9 with your fix.Thanks again :+1:  I will have a look at the cdn later when I have time, that will be helpful for downloading movies quicker.

**Comment by kodiokodi** [comment]
How to update the plugin on my Amazon fire TV ? I use superrepo. I am not able to update the plugin. It still shows 1.2.8

**Comment by junejosheeraz** [comment]
To get to super repo it will be some process I guess. Just download the repository directly from Github and install from there.

**Comment by junejosheeraz** [comment]
Just tested the plugin from Github repository directly and I can confirm its working now :+1:

**Comment by nagsharma32** [comment]
I have this issue. It doesnt load any movie though i switch browsers/clear cache!!!
